### ISSUE TITLE
Suffocation on ceiling and wall based grappling.

### ISSUE THREAD

**Issue by Mohl97** [yyon/grapplemod#10]
Me and my friend play on a private server together using a variety of mods, including this one and Smart Moving. We know to disable Smart Moving while using the grappling hooks, but if we touch walls or a ceiling while grappled to something, we take suffocation damage until we lose contact with that surface. It makes it rather hard to use grappling hooks to go up buildings because we take damage at every little bump and turn.

**Comment by yyon** [comment]
Ok, I disabled suffocation damage while using grappling hooks. Please re-download ( http://minecraft.curseforge.com/projects/grappling-hook-mod/files/2272750/download )

**Comment by Mohl97** [comment]
We're on 1.7.10. We've also encountered an issue where if we die while attached to a grappling hook, we immediately get connection terminations until the server restarts, and we restart our clients.

**Comment by yyon** [comment]
Ok, I ported the bugfixes to 1.7.10. Can you see if it works now?
