### ISSUE TITLE
i cannot shoot any grappling hook. anytime i click RMB it does not shoot anything. for 1.19.4. i check the keybinds and they keys are there at there default keys.[BUG]

### ISSUE THREAD

**Issue by CrazyJay98** [yyon/grapplemod#121]
**Describe the bug**

**Video / Screenshots**

**Version**
Mod version and Minecraft version

**Output Log**
An example log when the problem occurred. (Getting the log with the default Minecraft launcher: https://instant-structures-mod.com/tutorials/game-output-log/)
<details>
example log
</details>

**To Reproduce**
If you can, steps to reproduce the behavior, e.g.:

**Additional context**

**Comment by yyon** [comment]
This bug has been there for a long time, but unfortunately I was never able to track down why it happens, especially because it happens so rarely. If you can supply more information such as the log, that might help track down the bug

**Comment by epicyeeto** [comment]
yeah this mod is broken for me too
nothing works

**Comment by Harrier69** [comment]
I'm also unable to throw any hooks in 1.20.1

**Comment by What-The-Cheick** [comment]
> I'm also unable to throw any hooks in 1.20.1

Adding to this, tested binds and ones without conflict do not work
Unsure if this is caused by the inclusion of another mod

**Comment by ZurusonaKitsune** [comment]
Hi, I had the same problem too.
I'm using minecraft v1.20.1
I'm also using multiMC to manage different instances of minecraft. At first I thought it was probably a mod overriding the inputs so I made a clean setup with only grappling hook as the only mod but still got the same problem.
I then downgraded forge and it worked.
After a few tests the highest forge version compatible with grappling hook is v47.2.8

**Comment by Nyfaria** [comment]
1.20.1 and 47.1.3 is the highest i will port to on forge.
in 1.21 will be swapping to NeoForge.
so if its not working downgrade your forge version.

**Comment by What-The-Cheick** [comment]
I understand having the limit but you might as well have ended there, suggesting a downgrade feels counterintuitive considering that a lot of stuff requires higher forge versions

**Comment by Nyfaria** [comment]
And a lot of stuff stayed at 47.1.3? the Modding Ecosystem is in Flux atm, so you will need to pick your battles, what mods are worth keeping for X forge version.

**Comment by BaiterYamato** [comment]
Have you ever thought about port to fabric? acts as a fabric modder
