### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by HatelessHeart** [yyon/grapplemod#128]
**Describe the bug**
Mod wont work and wont keybind to anything in 1.20.1
ChatGBT says "It looks like you've encountered a Minecraft crash related to the application of mixins, specifically related to a mixin from the "grapplemod" mod. The error indicates that there's an issue with a field called f_90810_ in the target class net.minecraft.client.KeyMapping.

The root cause seems to be an InvalidMixinException, stating that the @Shadow field f_90810_ was not located in the target class net.minecraft.client.KeyMapping while using the reference map grapplemod-refmap.json.

To resolve this issue, you may want to check the configuration and code of the "grapplemod" mod, especially the mixin configuration (in the "grapplemod.mixins.json" file) and ensure that the target field f_90810_ is correctly defined in the class net.minecraft.client.KeyMapping."

**Comment by Nyfaria** [comment]
Sounds like another case of Forge making changes.
The mod works correctly on 47.1.3, which is the recommended version for this mod.
