### ISSUE TITLE
Motorized Grappling Hook operates erroneously when blocks are broken

### ISSUE THREAD

**Issue by JeffBobbo** [yyon/grapplemod#13]
![image](https://cloud.githubusercontent.com/assets/5425481/12053589/9f7369d0-af12-11e5-96b9-142d501a43c8.png)

As you can see, two grappling hooks but only one is 'active'.

Use the Motorized Grappling Hook to grapple onto a block in such a way that your route to the hook will be obstructed by another block. Once you've collided with this block the Motorized Grappling Hook will stop pulling on you, break the block you're resting against and you'll fall but the grappling hook stays in place. Right clicking will produce a new grappling hook and the old one will stay where it is.

These 'ghost hooks' can be removed by removing the block they're on.

Mod infos:
MCP: 9.05
FML: 8.0.99.99
Minecraft Forge: 11.14.3.1450
Player API: 1.4
Smart Core: 1.2.1
grapplemod: 1.8-v3
Smart Moving: 16.2
Smart Render: 2.1

**Comment by yyon** [comment]
When I tried to reproduce this bug, I found that if you destroy a block that a grappling hook was previously attached to (but not anymore), it causes buggy behaviour. I fixed this bug in version 4. Can you redownload and check if this bug is fixed?

**Comment by JeffBobbo** [comment]
Seems this is fixed, nice!
