### ISSUE TITLE
[BUG] Button To Throw Grappling Hook Not Working

### ISSUE THREAD

**Issue by AngelSkyheart** [yyon/grapplemod#132]
Pressing right click does not throw the grappling hook. I've tried rebinding, nothing works. I ended up looking for answers, and found something on curseforge that is NOT on Modrinth where I downloaded it: 

Broken on Forge 47.1.4+, please use 47.1.3 or older

This would have been nice to know _before_ I downloaded the mod. Though I suppose since everything else still works, I'll be keeping it in my modpack regardless. What I don't get is why it doesn't look like this issue seems to be in the issues section of github at all. So I'm making this bug report so I can specifically ask what about the newer versions of forge is breaking the ability to use the grappling hook? Is there anything happening to fix the issue? I've only seen a single comment on the curseforge page about how it might be updated for neoforge but that wasn't even from you. Is an update for Neoforge actually happening? I honestly hope not, as I have no idea if Neoforge can even run regular Forge mods or not...

Either way, some information about what's going on would be appreciated, and I hope it's not too much trouble.

Also if you could update the Modrinth page to show that warning, I would appreciate it.

Minecraft 1.20.1
Forge 47.2.20
Modpack All The Forge 10 v10.7 (Personally Customized with extra mods)
**_Custom Added Server Side Mods_**
- Achievement Optimizer 1.0.2
- Actually Unbreaking 0.2.0
- Adaptive Performance Tweaks Core 11.0.0
- Adaptive Performance Tweaks Player 11.0.0
- AI Improvements 1.20-0.5.2
- _AIOT Botania 4.0.4_
- Alternate Current 1.7.0
- Axes Are Weapons 1.7.3
- Easy Elytra Takeoff 4.2
- _Better Combat 1.8.4_
- Better Safe Bed 9
- Big Brain 1.7.3
- Boids 1.1.1
- _Botania 443_
- _Botanic Pledge 0.6.0.2 (mod.toml custom fixed)_
- Bottle Your XP 3.3
- Cave Spider Spawn 1.1
- Companion 5.0.1
- Conduits Prevent Drowned 3.6
- Edibles 4.3
- Embedded Assets 1.1.3
- _Ender Zoology 8.0.2_
- _Ex Machinis 3.0.0_
- _Ex Nihilo Sequentia 5.0.0 b6 (mod.toml custom fixed)_
- Farsighted Mobs 1.1
- _Garden of Glass 1.12_
- Gotta Go Fast Lexforge 2.0.1
- _**Grappling Hook Mod v13**_
- Harvest With Ease 8.0.1.0
- Infinite Trading 4.3
- Inventory Totem 3.2
- Kelp Fertilizer 3.2
- _LibX 5.0.12 (Mythic Botany 4.0.3 Dependent)_
- _Mana And Artifice 3.0.0.10-all_
- _More Red 4.0.0.4_
- _More Red-CCT Compatibility 1.0.0_
- _MythicBotany 4.0.3_
- Nametag Tweaks 3.2
- _Nature's Aura 39.4_
- _Nova Core 1.0.0 b3 (Ex Nihilo Sequentia Dependent)_
- Nullscape 1.2.4
- _Nyfs Spiders 2.1.1_
- Passive Shield 3.4
- _Player Animation Lib 1.0.2-rc1 (Better Combat Dependent)_
- _Point Blank 1.0.2_
- _Point Blank Recipes - Raygun_
- _Puzzles Lib 8.1.17 (Ender Zoology Dependent)_
- Random Bonemeal Flowers 4.5
- Scaffolding Drops Nearby 3.2
- Shulker Drops Two 3.3
- _Smallships 2.0.0-b1.1_
- Snowballs Freeze Mobs 3.3
- _Solarcraft 3.2.2_
- Stack Refill 4.2
- Stalker Creepers 1.20.1.1
- Thorny Busy Protection 1.2
- Underwater Enchanting 2.7
- Wool Tweaks 3.3
- _Workers 1.7.6_
- Villager Names 7.3

**Comment by Nyfaria** [comment]
#130 #127 #126 
its in Closed Issues because we aren't support newer forge versions and will be continuing with NeoForge in 1.21.

**Comment by AngelSkyheart** [comment]
> #130 #127 #126 its in Closed Issues because we aren't support newer forge versions and will be continuing with NeoForge in 1.21.

Thank you for the reply I appreciate it. ^_^

**Comment by Damaskox** [comment]
> #130 #127 #126 its in Closed Issues because we aren't support newer forge versions and will be continuing with NeoForge in 1.21.

I would like to know @Nyfaria 
- Will you ever support Forge again
- Why NeoForge over Forge?

**Comment by Nyfaria** [comment]
> > #130 #127 #126 its in Closed Issues because we aren't support newer forge versions and will be continuing with NeoForge in 1.21.
> 
> I would like to know @Nyfaria 
> - Will you ever support Forge again
> - Why NeoForge over Forge?

We will no longer support Forge. Ever. It is dying anyway.

NeoForge is the true successor to Forge.
The owner of forge was super problematic including harassing female developers. So the forge team left him behind to make NeoForge. It is the true Mod Loader.

**Comment by Damaskox** [comment]
@Nyfaria Oh wow. Oof.
Good to know.

Is there some link I can read further in this/these incidents?

**Comment by Nightmar0** [comment]
Bruh. Plz just add compatibility with forge 47.3.22. I'm using that in my modpack, and have spent a lot of time working on it. PLz plz plz.

**Comment by KostromDan** [comment]
> > > [#130](https://github.com/yyon/grapplemod/issues/130) [#127](https://github.com/yyon/grapplemod/issues/127) [#126](https://github.com/yyon/grapplemod/issues/126) its in Closed Issues because we aren't support newer forge versions and will be continuing with NeoForge in 1.21.
> > 
> > 
> > I would like to know [@Nyfaria](https://github.com/Nyfaria)
> > 
> > * Will you ever support Forge again
> > * Why NeoForge over Forge?
> 
> We will no longer support Forge. Ever. It is dying anyway.
> 
> NeoForge is the true successor to Forge. The owner of forge was super problematic including harassing female developers. So the forge team left him behind to make NeoForge. It is the true Mod Loader.

Have you reported it to them? If not, it will never be fixed. I haven't seen any issues related to this problem from you or other collaborators in the issue tracker, so I assume you haven't reported it.
As I understand it, you are supporting NeoForge in their conflict by taking a difficult approach, but even the NeoForge team has currently dropped support for 1.20.1 and is recommending the use of Lex Forge. I acknowledge that you plan to port the mod to 1.21 exclusively on NeoForge, as is the common practice, including my own, but I think there is no reason to cause issues for the large 1.20.1 modding community, which remains the current standard and will remain it for many years.

**Comment by Nyfaria** [comment]
> > > > [#130](https://github.com/yyon/grapplemod/issues/130) [#127](https://github.com/yyon/grapplemod/issues/127) [#126](https://github.com/yyon/grapplemod/issues/126) its in Closed Issues because we aren't support newer forge versions and will be continuing with NeoForge in 1.21.
> > > 
> > > 
> > > I would like to know [@Nyfaria](https://github.com/Nyfaria)
> > > 
> > > * Will you ever support Forge again
> > > * Why NeoForge over Forge?
> > 
> > 
> > We will no longer support Forge. Ever. It is dying anyway.
> > NeoForge is the true successor to Forge. The owner of forge was super problematic including harassing female developers. So the forge team left him behind to make NeoForge. It is the true Mod Loader.
> 
> Have you reported it to them? If not, it will never be fixed. I haven't seen any issues related to this problem from you or other collaborators in the issue tracker, so I assume you haven't reported it. As I understand it, you are supporting NeoForge in their conflict by taking a difficult approach, but even the NeoForge team has currently dropped support for 1.20.1 and is recommending the use of Lex Forge. I acknowledge that you plan to port the mod to 1.21 exclusively on NeoForge, as is the common practice, including my own, but I think there is no reason to cause issues for the large 1.20.1 modding community, which remains the current standard and will remain it for many years.

There is a reason, and that reason is, I don't think anyone should be using Lexforge at all ever anymore.

**Comment by KostromDan** [comment]
> > > > > [#130](https://github.com/yyon/grapplemod/issues/130) [#127](https://github.com/yyon/grapplemod/issues/127) [#126](https://github.com/yyon/grapplemod/issues/126) its in Closed Issues because we aren't support newer forge versions and will be continuing with NeoForge in 1.21.
> > > > 
> > > > 
> > > > I would like to know [@Nyfaria](https://github.com/Nyfaria)
> > > > 
> > > > * Will you ever support Forge again
> > > > * Why NeoForge over Forge?
> > > 
> > > 
> > > We will no longer support Forge. Ever. It is dying anyway.
> > > NeoForge is the true successor to Forge. The owner of forge was super problematic including harassing female developers. So the forge team left him behind to make NeoForge. It is the true Mod Loader.
> > 
> > 
> > Have you reported it to them? If not, it will never be fixed. I haven't seen any issues related to this problem from you or other collaborators in the issue tracker, so I assume you haven't reported it. As I understand it, you are supporting NeoForge in their conflict by taking a difficult approach, but even the NeoForge team has currently dropped support for 1.20.1 and is recommending the use of Lex Forge. I acknowledge that you plan to port the mod to 1.21 exclusively on NeoForge, as is the common practice, including my own, but I think there is no reason to cause issues for the large 1.20.1 modding community, which remains the current standard and will remain it for many years.
> 
> There is a reason, and that reason is, I don't think anyone should be using Lexforge at all ever anymore.

For 1.21: yes. For 1.20.1 where is no way to use it, since NeoForge Team recommends using LexForge.
Not all mods ported to 1.21, not all mods stable enought. For many reasons I can't use 1.21 for my modpack. Maybe after 1-2 years, but currently - absolutly not. I lack too many things which are mandotory for my modpack.

You don't think, but currently modding community is very actively using it, and suffering bc of lack of your mod.

**Comment by Nyfaria** [comment]
> > > > > > [#130](https://github.com/yyon/grapplemod/issues/130) [#127](https://github.com/yyon/grapplemod/issues/127) [#126](https://github.com/yyon/grapplemod/issues/126) its in Closed Issues because we aren't support newer forge versions and will be continuing with NeoForge in 1.21.
> > > > > 
> > > > > 
> > > > > I would like to know [@Nyfaria](https://github.com/Nyfaria)
> > > > > 
> > > > > * Will you ever support Forge again
> > > > > * Why NeoForge over Forge?
> > > > 
> > > > 
> > > > We will no longer support Forge. Ever. It is dying anyway.
> > > > NeoForge is the true successor to Forge. The owner of forge was super problematic including harassing female developers. So the forge team left him behind to make NeoForge. It is the true Mod Loader.
> > > 
> > > 
> > > Have you reported it to them? If not, it will never be fixed. I haven't seen any issues related to this problem from you or other collaborators in the issue tracker, so I assume you haven't reported it. As I understand it, you are supporting NeoForge in their conflict by taking a difficult approach, but even the NeoForge team has currently dropped support for 1.20.1 and is recommending the use of Lex Forge. I acknowledge that you plan to port the mod to 1.21 exclusively on NeoForge, as is the common practice, including my own, but I think there is no reason to cause issues for the large 1.20.1 modding community, which remains the current standard and will remain it for many years.
> > 
> > 
> > There is a reason, and that reason is, I don't think anyone should be using Lexforge at all ever anymore.
> 
> For 1.21: yes. For 1.20.1 where is no way to use it, since NeoForge Team recommends using LexForge. Not all mods ported to 1.21, not all mods stable enought. For many reasons I can't use 1.21 for my modpack. Maybe after 1-2 years, but currently - absolutly not. I lack too many things which are mandotory for my modpack.
> 
> You don't think, but currently modding community is very actively using it, and suffering bc of lack of your mod.

Fun Fact: The more you argue with mod devs like this, the less likely they will cave to your demands.

**Comment by KostromDan** [comment]
Anyways my thesis is same. you are just causing suffering to the 1.20.1 Community, which is not to blame for anything. For 1.21 neo is already mainstream each modpack  is using it. For 1.20.1 each modpack using Minecraft Forge. Do you want to harm Lex in any way? He doesn't give a damn about it. However, the largest community is currently suffering from this 1.20.1. Not Lex, but the community.
