### ISSUE TITLE
[BUG] Grappling Hook not working

### ISSUE THREAD

**Issue by DARKLOL680** [yyon/grapplemod#135]
**Describe the bug**
the Grappling Hook mod just doesn't work, the items and block are here but i cannot use any grappling hook
i tried changing keybinds but it did not work 

**Video / Screenshots**

![2024-03-24_12 14 12](https://github.com/yyon/grapplemod/assets/121734819/ff35838a-14b0-4bbf-8f0b-55bcc4d445e3)

**Version**
Forge 1.20.1

**Comment by AstroQue** [comment]
were you able to fix this bug? the same thing is happening to me :/

**Comment by Nyfaria** [comment]
#130 #127 #126 
duplicate. Problem has been responded to time and time again. Please check closed issues before making issues on githubs.
