### ISSUE TITLE
[BUG] Grappling Hooks do not work

### ISSUE THREAD

**Issue by BeckPhillips** [yyon/grapplemod#136]
**Describe the bug**
Simply put: I cannot use my grappling hook, in any capacity. I have tried using it in creative, survival, and even tried creating a new grappling hook and even a new world, in case there was something wrong with mine.

**Version**
V13-1.20.1 Forge.

**To Reproduce**
1. Make or obtain a grappling hook
2. Try to use it
3. nothing happens.

**Additional context**
I've created a fresh install that just contains Cloth Config and Grappling Hooks, and it still doesn't work, so I'm doubting that it's another mod in my modpack with 108 mods.

**Comment by Nyfaria** [comment]
#130  #127 #126 #135 
Duplicate Issue

**Comment by BeckPhillips** [comment]
I think that the solution of "downgrade" isn't a great one, since some other mods might require a specific version of forge.
Are there any plans to figure out what the issue is and/or fix the problem?

**Comment by Nyfaria** [comment]
There is no issue with the mod, the issue is with forge. So there is no plans to fix forge from our end, no.

**Comment by Nightmar0** [comment]
🙏Plz update mod.
