### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by IsaDucko** [yyon/grapplemod#138]
Grappling hook does not work

After making a version with only this mod, the none of the grappling hooks function, the enderstaff does.
Playing on latest mod version with 1.20.1 forge

**Comment by yyon** [comment]
It's broken on Forge 47.1.4+, make sure you are using forge 47.1.3 or older

**Comment by PabuUwU** [comment]
please update to 47.2.17

**Comment by Nyfaria** [comment]
> please update to 47.2.17

I'm sorry, but we won't be doing that.
