### ISSUE TITLE
Contributions and suggestions

### ISSUE THREAD

**Issue by JeffBobbo** [yyon/grapplemod#14]
I'm interested in contribution, and not really sure where to ask about this (in general, projects have a CONTRIBUTING file for direction on this).

I also have (a) suggestion or query about something you may already be planning (specifically: Are you planning to implement the ability to (de)select which blocks it's possible to grapple on to), where is best to ask about this kind of thing in future?

**Comment by yyon** [comment]
Just make an issue on github and label it enhancement/question.
As for the ability to select which blocks it's possible to grapple on to, that functionality is already implemented. 
Just use the grapplingBlocks gamerule, for example:
/gamerule grapplingBlocks minecraft:cobblestone,minecraft:stone

**Comment by JeffBobbo** [comment]
We can't label issues (that's a permission you have to grant us, like being able to write directly to the repository).

Hearing that's a gamerule is cool, how does that work though, if I run that command does that mean the only blocks I can grapple are cobblestone and stone?

**Comment by yyon** [comment]
/gamerule grapplingBlocks minecraft:cobblestone,minecraft:stone
means that it will only attach to cobblestone and stone.
