### ISSUE TITLE
[I AM NOT SURE IF THIS IS A BUG OR INCOMPATIBLITY] grappling hook not throwing

### ISSUE THREAD

**Issue by madaBoda** [yyon/grapplemod#140]
i just throw the thing it is not throwing idk why also if it is incompatibility i do not know the mod

1.20.1 latest version of the mod

log (also its like 7000 lines so good luck if you wanna read it)
[latest.log](https://github.com/user-attachments/files/16472005/latest.log)

**Comment by yyon** [comment]
It's broken on Forge 47.1.4+, make sure you are using forge 47.1.3 or older

**Comment by madaBoda** [comment]
aight thx : )

**Comment by madaBoda** [comment]
btw will it be fixed?

**Comment by Nyfaria** [comment]
no
