### ISSUE TITLE
[INCOMPATIBILITY]

### ISSUE THREAD

**Issue by pablocbamorim** [yyon/grapplemod#143]
Grappling hook won’t shoot if playing on any version of forge past 47.1.3
The game launches normally, ender staff functions normally, grappling hook refuses to shoot (I notice a little drop on fps at the moment i press right click)

[https://www.reddit.com/r/feedthebeast/s/s8SLHrKXV2](url)

Forge 47.1.3

**To Reproduce**
Try using the grappling hook on any forge version past 47.1.3

**Comment by Nyfaria** [comment]
Yes, we know.
![Screenshot_20241120_193842_Chrome.jpg](https://github.com/user-attachments/assets/7df1b95e-7517-4a29-bc36-46d4e0b08e59)

**Comment by KostromDan** [comment]
@Nyfaria 47.1.3 is VERY VERY old version.
A ton of mods don't support it. This makes the mod unusable for modpacks. We want to use it—players love it—but we can't include it. So, we're eagerly waiting for compatibility with modern Forge 1.20.1.

**Comment by Nyfaria** [comment]
> [@Nyfaria](https://github.com/Nyfaria) 47.1.3 is VERY VERY old version. A ton of mods don't support it. This makes the mod unusable for modpacks. We want to use it—players love it—but we can't include it. So, we're eagerly waiting for compatibility with modern Forge 1.20.1.

My Morals rise above your want to use the mod. I am sorry.
