### ISSUE TITLE
Request/Suggestion - Change grapplinghook appearance

### ISSUE THREAD

**Issue by t2pellet** [yyon/grapplemod#21]
Hello, I found that the fishing rod line, which is what this mod uses to render I believe, often goes invisible if it is thrown too far, or just as one is swinging.
I would suggest making it so that it renders a thicker line and that it be tweaked so it never goes invisible.
I know this would be difficult though, so no pressure.

**Comment by yyon** [comment]
Are you using the newest version? I changed it. It uses the renderer for the lead and it only disappears when you aren't looking at it or it's in an unrendered chunk.

**Comment by Poseidon5001** [comment]
Latest version. It disappears when it is 4-6 chunks away. My render distance is set at 16.

**Comment by yyon** [comment]
The renderer was rewritten in v7 (for 1.9.4 and 1.8.9). Try using one of these versions and see if you still have the problem.

**Comment by Poseidon5001** [comment]
I am using this mod in a Private mod pack (only me and 1 friend use it, it isnt being distributed) which is for version 1.7.10. I tested those versions, they do solve the problem :/
Unfortunately Im stuck on 1.7.10 due to other mods not being updated.
