### ISSUE TITLE
Suffocation / Block Damage when grappling

### ISSUE THREAD

**Issue by t2pellet** [yyon/grapplemod#22]
Hello, when I grapple and am pulled near a wall or ceiling I take large amounts of damage, a few hearts a second. This is on the latest version for 1.7.10

**Comment by yyon** [comment]
I'm pretty sure v6 for 1.7.10 handles suffocation damage. Are you on v6? Does the problem still occur on v7? Are you using any other mods?

**Comment by Poseidon5001** [comment]
There are multiple other mods, however none that I could see would affect suffocation damage. I am using v6 (latest version for 1.7.10). I will test with the mod by itself.
