### ISSUE TITLE
Anti-Cheat triggered due to speed in multiplayer, possible to fix in mod?

### ISSUE THREAD

**Issue by nitefang** [yyon/grapplemod#27]
The speed the user can attain while using these hooks, especially the magnetic hooks, cause the multiplayer server to flag the user as cheating and stops them in mid-air. This cannot be stopped with current vanilla Minecraft gamerules such as disableElytraFlightCheck or by changing the server.properties file to allow flight. Is it possible to fix this in the mod itself?

**Comment by yyon** [comment]
Sorry for the late reply. I released version 8 which should fix this bug. You'll still need to enable flight in the server.properties file, but v8 should stop the "player moved too quickly" bug. Update and let me know if you have any problems.
