### ISSUE TITLE
request for configurable ranges for hooks

### ISSUE THREAD

**Issue by Divineaspect** [yyon/grapplemod#28]
I'm having some server related lag caused by the amazing movement speeds which these hooks make possible.

Among other things being able to project hooks farther away then the chunk loading distance is problematic.

The ability to config hook distance could go a long way to resolve this issue, as well as enable a few options for pack makers.

**Comment by yyon** [comment]
There already is a game rule for length (grappleLength  I think? Check the mod description on curse or Minecraft forum).

**Comment by Divineaspect** [comment]
I'm requesting a configuration file not game rules.
