### ISSUE TITLE
[1.10.2] Does not work after teleporting

### ISSUE THREAD

**Issue by ChaoticLogic** [yyon/grapplemod#33]
Playing single player survival using Xairo Minimap. After teleporting to a waypoint set in Xairo, the grappling hook will not work. What happens is when I try to grapple to a surface the hook will go out and stick, but nothing happens. If I am not aiming at a block close enough, the hook will stick right where I'm at, and again, nothing happens. The ropes will remain in place until I close Minecraft and start again.

**Comment by Terpo** [comment]
We have the same problem in 1.11.2 but mainly with Waystones from this mod: https://github.com/blay09/Waystones
grapplemod-v9-1.11.2.jar
Waystones_1.11.2-3.0.16.jar
with forge 2386

**Comment by yyon** [comment]
I checked in the newest version (v10) and I wasn't able to reproduce the problem. Maybe it's fixed?
