### ISSUE TITLE
Suggestion/Request Config Option to Disable Durability

### ISSUE THREAD

**Issue by The-PurpleOrange** [yyon/grapplemod#34]
Hey I'm in the progress of making a puzzle map series revolving around solving logic puzzles primarily by using this mod, and was wondering if you could add a config option to disable durability? It would also just save me from constantly having to craft 2-3 an in-game day since these are my primary mode of transport now, Extrautili2 creative flight can suck it, nothings more fun than swinging my way around my sky islands. Awesome mod keep up the great work!

**Comment by yyon** [comment]
Hi, sorry for the late reply. Here's a version where I just disabled damaging the items. This is for 1.10.2, let me know if you want a different version. 
https://drive.google.com/file/d/0Bwum1DVR9SNNOTZ1UTFIQUIwd3c/view?usp=sharing

**Comment by brnnnrsmssn** [comment]
i would really like this feature, or a build that disabled durability for the latest version of the mod on 1.12.2.

looking through the code, i am not good at coding, it looks like all the durability loss is handled by methods in the grappleBow class. and you could replace them with a variable set in the config to enable, disable, or change the amount of durability loss on use.
