### ISSUE TITLE
Feature request: config file option for maximum range

### ISSUE THREAD

**Issue by Alphanos** [yyon/grapplemod#41]
Good evening,

Thank you for your excellent mod.  I really like the way these grappling hooks play.  They have a great feel to them.

My only hesitation with including them in a pack I am working on is that I feel like the unlimited range makes them extremely powerful.  E.g. if you can see a slime island in the far distance of your rendered chunks, no problem, one of these grappling hooks can get you up there right away.

If it would fit with your intended design for the mod, I think a great feature would be to add a config file option making it possible to set a maximum range the hooks can travel before auto-retracting and returning to the player.  Or depending on what is easier to code, just prevent them from firing in the first place if the aimed-at target is beyond the maximum range.

Thank you for your great mod!

**Comment by adamk33n3r** [comment]
@Alphanos You can already set the gamerule of `grapplingLength` but I would REALLY prefer a config file.
