### ISSUE TITLE
Grappling hooks don't launch themselves when I use them

### ISSUE THREAD

**Issue by levilips123** [yyon/grapplemod#44]
They kinda stick to the player. every grappling hook shows  this behavior . hope you will fix this. thanks for paying attention to this problem

**Comment by Leonature26** [comment]
I had the same issue as you. Hook sticking to player everytime even on single player. What I did was used an upgrade block on the grappling hook and it shoots fine now. Maybe it resets a bug or something. (Might help others who had same issues looking for solutions)

**Comment by yyon** [comment]
Duplicate of #88
