### ISSUE TITLE
GrappleMod crashes 1.12.2 Forge server as of v11 release

### ISSUE THREAD

**Issue by SalmonSays** [yyon/grapplemod#47]
Just tested on a fresh forge server, v10 loads/launches just fine, but v11 results in a NoClassDefFound error- detailed here:

https://hastebin.com/xevapumeho.rb

The offending line is "Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiScreen", looks like in v11 a client-only class gets mistakenly accessed by both client and server? I'm tentatively hopeful this is an easy hotfix.

**Comment by yyon** [comment]
Fixed it. [https://drive.google.com/open?id=1ZiIkOeNqknCQzLy1Tu2B3K7pdZNIBuFT](https://drive.google.com/open?id=1ZiIkOeNqknCQzLy1Tu2B3K7pdZNIBuFT)
The fix should be released on curse sometime soon.
Let me know if you have any more problems on servers

**Comment by SalmonSays** [comment]
Works great, I really appreciate the quick turnaround!
