### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by JeffBobbo** [yyon/grapplemod#5]
I did a crash!

Was swinging around using the Grappling Hook, used space to jump off and the when I hit space it died.

https://gist.github.com/JeffBobbo/730e0970eef4d46ef4e4

**Comment by yyon** [comment]
I wasn't able to reproduce this crash, but I changed some code which I think might have caused the problem, so let me know if this happens again with the new version.

**Comment by JeffBobbo** [comment]
It's unlikely I'll be able to reproduce, it happened randomly and I'm not sure what I done to cause it (other than what I said).

**Comment by JeffBobbo** [comment]
I done it again (with the 1.8-v3 version). Crash looks like it's the same thing: https://gist.github.com/JeffBobbo/cd08733be31588d0268c

Done the same thing, had grappled onto some blocks, was against the geometry and pressed space to pop up and land higher than I was. Crashed when I pressed space.

**Comment by yyon** [comment]
I changed it so it will catch this exception now. Can you try to reproduce the bug again?
