### ISSUE TITLE
only grapple hook available

### ISSUE THREAD

**Issue by sparton76** [yyon/grapplemod#60]
Looked up all the recipes in JEI- everything works properly in my custom modpack (very few mods), but when using this in RLCraft the only item actually in the mod is the grappling hook. no modification table shows up, not even the ender staff. If this is because of a setting in RLCraft despite the mod not being in the modpack originally, then i don't know where to find it.

**Comment by yyon** [comment]
It's definitely a setting in RLCraft. I don't play RLCraft, but there's probably another mod that is used to remove items. It looks like CraftTweaker is part of RLCraft, I might check in CraftTweaker. If not, check the list of mods (https://www.curseforge.com/minecraft/modpacks/rlcraft/relations/dependencies) for a mod that can remove items or something.
