### ISSUE TITLE
repeller and enderstaff too unbalanced

### ISSUE THREAD

**Issue by ThsHaunted124** [yyon/grapplemod#64]
ive used this mod in multiple modpacks in a server witch my friends. what ive noticed over time is that nobody used a grappling hook, instead they use the repeller and enderstaff to get around because its a lot faster, ive tried to disable the crafting recipes of these two items with crafttweaker but it does not work.

**Comment by democat3457** [comment]
There's a config option to disable the ender staff.

**Comment by ThsHaunted124** [comment]
Ive tried multiple settings in the config folder but none seemed to have worked. could you tell me where i can find the setting and what i have to type in to disable the repeller and enderstaff? 

so far i have tried setting the max repelforce to 0.0. And ive also tried setting the enable_repelforce,  enable_repel and enable_enderstaff to the number "1".

**Comment by democat3457** [comment]
Set it to 0 to disable.

**Comment by ThsHaunted124** [comment]
the enable_ect... options are set to 0 by default

with these default settings i can still craft and use them

https://imgur.com/a/qb6DhKf

**Comment by yyon** [comment]
Those options are just for the grappling hook upgrades, sorry that the names aren't clear. Unfortunately there isn't any config options right now to disable those items. You'll have to figure out why crafttweaker isn't working, or use a similar mod.
