### ISSUE TITLE
*Suggestion* Blacklist/Whitelist For Blocks

### ISSUE THREAD

**Issue by JordanCJbrowne** [yyon/grapplemod#66]
Any way to setup an easy system (possibly for 1.12.2?) where we can blacklist/whitelist what blocks the grappling hook can attach to? 

For example, I could "Blacklist All", and then "Whitelist" Oak Wooden Planks. 

Then the grappling hook would only be able to attach to/loop around Oak Wooden Planks and no other block, if the user tries, it just bounces back and doesn't take dmg/still takes dmg, or even an option for that as well.

**Comment by yyon** [comment]
Implemented as the grapplingBlocks / grapplingNonBlocks config options
