### ISSUE TITLE
SUGGESTION: (sorry to bother you) 1.16/1.17

### ISSUE THREAD

**Issue by ItsMrZ** [yyon/grapplemod#69]
could you possibly make a port of this mod for 1.16.5/1.17? im currently making an emmersive vanilla modpack, and thought this was a really nice mod, but was saddened to find that it is not for the 1.16 version of minecraft. i am sorry to bother you with this suggestion as i know you haven't worked on this mod in 2 years, or at least haven't updated it, but i only ask that you consider doing so. thank you for your time, sir/ma'am.

                                                                                           sincerely,
                                                                                                    ItsMr.Z

**Comment by ItsMrZ** [comment]
just realized this is issue 69 so you must listen now

**Comment by Ch1216** [comment]
youve got to close it now that its done
